# Generated by Django 3.0.5 on 2020-07-11 21:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('episode_nb', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64, unique=True)),
                ('opening_crawl', models.TextField(null=True)),
                ('director', models.CharField(max_length=32)),
                ('producer', models.CharField(max_length=128)),
                ('release_date', models.DateField()),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('climate', models.TextField()),
                ('diameter', models.IntegerField()),
                ('orbital_period', models.IntegerField()),
                ('population', models.BigIntegerField()),
                ('rotattion_period', models.IntegerField()),
                ('suface_water', models.FloatField()),
                ('terrain', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('birth_year', models.CharField(max_length=32)),
                ('gender', models.CharField(max_length=32)),
                ('eye_color', models.CharField(max_length=32)),
                ('hair_color', models.CharField(max_length=32)),
                ('height', models.IntegerField()),
                ('mass', models.FloatField()),
                ('homeworld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ex09.Planets')),
            ],
        ),
    ]
